unit TestThShape;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, ThShape, FMX.Types;

type
  // Test methods for class TThLine

  TestTThLine = class(TTestCase)
  strict private
    FThLine: TThLine;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  end;
  // Test methods for class TThRectangle

  TestTThRectangle = class(TTestCase)
  strict private
    FThRectangle: TThRectangle;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  end;

implementation

procedure TestTThLine.SetUp;
begin
  FThLine := TThLine.Create(nil);
end;

procedure TestTThLine.TearDown;
begin
  FThLine.Free;
  FThLine := nil;
end;

procedure TestTThRectangle.SetUp;
begin
  FThRectangle := TThRectangle.Create(nil);
end;

procedure TestTThRectangle.TearDown;
begin
  FThRectangle.Free;
  FThRectangle := nil;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTThLine.Suite);
  RegisterTest(TestTThRectangle.Suite);
end.

