unit TestThItem;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, FMX.Forms, FMX.Layouts, System.Types,
  ThItem;

type
  // Test methods for class IThItem

  TestIThItem = class(TTestCase)
  strict private
    FThItem: TThItem;

    FForm: TForm;
    FScrollBox: TScrollBox;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestAdd;
  end;

implementation

uses
  FMX.TestLib.Mouse;

procedure TestIThItem.SetUp;
begin
  // TODO: Initialize FIThItem

  FForm := TForm.Create(nil);
  FForm.Width := 600;
  FForm.Height := 600;

  FScrollBox := TScrollBox.Create(nil);
  FScrollBox.Parent := FForm;
  FScrollBox.Width := 300;
  FScrollBox.Height := 300;
  FScrollBox.Position.Point := PointF(0, 0);
//  FScrollBox.Parent := ;

end;

procedure TestIThItem.TearDown;
begin
  FScrollBox.Free;
  FScrollBox := nil;

  FForm.Free;
end;

procedure TestIThItem.TestAdd;
begin
  FThItem := TThItem.Create(FScrollBox);
  FThItem.Parent := FScrollBox;
  FThItem.Width := 100;
  FThItem.Height := 100;
  FThItem.Position.Point := PointF(50,50);

  MouseDown(PointF(101, 101));

  Check(FThItem.Visible);



end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestIThItem.Suite);
end.

