unit TestThCircle;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, BaseTestUnit, FMX.Types, FMX.Forms,
  System.UITypes, System.Types, System.SysUtils, FMX.Controls, System.UIConsts;

type
  // Test methods for class TThCircle

  // #21 캔버스에 원을 추가한다.
  TestTThCircle = class(TBaseTestUnit)
  published
    procedure TestItemFactory;

    procedure TestDrawCircle;
  end;

implementation

uses
  FMX.TestLib, ThItem, ThShape, ThItemFactory, ThConsts;

{ TestTThCircle }

procedure TestTThCircle.TestItemFactory;
var
  Item: TThItem;
begin
  // 1300 is Circle
  Item := ItemFactory.Get(1300);
  try
    Check(Assigned(Item));
  finally
    if Assigned(Item) then
      Item.Free;
  end;
end;

procedure TestTThCircle.TestDrawCircle;
var
  Item: TThItem;
begin
  ShowForm;

  // Draw
  DrawCircle(50, 50, 200, 200);

  // Select
  TestLib.RunMouseClick(100, 100);
  Item := FCanvas.SelectedItem;

  Check(Assigned(Item), 'Check SelectedItem');
  Check(Item.ClassType = TThCircle, 'Check Class type');

  Check(Item.Position.X = 50, Format('X = %f', [Item.Position.X]));
  Check(Item.Width = 150,     Format('Width = %f', [Item.Width]));
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTThCircle.Suite);
end.

